### ISSUE TITLE
bug: tuple[] generated type is incorrect?

### ISSUE THREAD

**Issue by Yuripetusko** [wagmi-dev/abitype#72]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.2.5

### TypeScript Version

4.7.4

### Current Behavior

for a given function in ABI

```
{
    inputs: [{ internalType: 'uint64[]', name: 'partIds', type: 'uint64[]' }],
    name: 'getParts',
    outputs: [
      {
        components: [
          { internalType: 'enum IRMRKBaseStorage.ItemType', name: 'itemType', type: 'uint8' },
          { internalType: 'uint8', name: 'z', type: 'uint8' },
          { internalType: 'address[]', name: 'equippable', type: 'address[]' },
          { internalType: 'string', name: 'metadataURI', type: 'string' },
        ],
        internalType: 'struct IRMRKBaseStorage.Part[]',
        name: '',
        type: 'tuple[]',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  }
```

abittype tells me that the return value is (Array of objects)

```
readonly {itemType: number, z: number, equippable: readonly `0x${string}`[], metadataURI: string}[]
```

but in reality it is (Array of arrays)

```
[number, number, `0x${string}`, string][]
```

Not 100% sure if the problem is on abitype side?

### Expected Behavior

return type to be `readonly [number, number, `0x${string}`, string][]`

### Link to Minimal Reproducible Example ([TypeScript Playground](https://tsplay.dev/wjQvkW))

not clear how to present reproducable example

**Comment by Yuripetusko** [comment]
This is what typechain generates for this output

```
export type PartStructOutput = [number, number, string[], string] & {
    itemType: number;
    z: number;
    equippable: string[];
    metadataURI: string;
  };
  
  getParts(
      partIds: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<[IRMRKBaseStorage.PartStructOutput[]]>;
```

**Comment by tmm** [comment]
Looks correct to me! ABIType converts tuples/structs with named components to objects (with the keys set to the names of the components). If one of the components isn't named (e.g. `name: ''` or `name` doesn't exist), the ABIType falls back to array syntax.

In this example, all components are named so the result is an array of objects. If one of the components was not named, then it would be an array of arrays. Check out [this TypeScript playground](https://www.typescriptlang.org/play?#code/PQKhCgAIUhBBneBTATgF0gBwIYuwWyTVUgEt5IB7AM0m0nkyQGNTrTnI0BPJgOigRokAAI48+SAH0AbtgA2AVySQAtJABqC5VwAW2DPF2VF8gCaQARitJmkAOzQcFXSl14qABgBVPA6MDgSAAemJTokNSK9sxOlPaQIUyx3h4APN4AfAAUstpIAFyQ3gCURTKUtpAA3gC+4OCk+GER1XCWpAAKuAREqN6UnShNpE4ySKlMkLWRKJSSAOTYHTxMCw3AwJAAymgoirGQAO6jupD2vRbM82H2Dmjw4KsqAEpI8KYYALztXT2ExBQAyGIzGE3S1SgkGuzXi93gRQA2lDIDUUaiyI5UBd5JNCpAFg5FJIAJIvACyLwA0gAhbDIXbhbAAcyQfBJxHwePWGIxF0IRQWoyQXI8PN57iYgsUpEcAA5xajagAadFtWWAnF46UahUAbnOvUFAC8Fgbnjr5QtpqreeqsSgtR5BdgzGYUO94IiALpmw0CglIACOMswOEs8iQfotBNd7s9PutKrVmM1Cm1BPge1lzL9-PxCwBroM2AAqi8SdHnZns-Zczaod6oRrsenqwss-tDmTKbT6UhGXhWXxuuhE1D84LxTGFmhFJhI+PapkgqEWGg8Wk3h95GgcsjUZDecLRVLIABGW0Y41FABMV9RwdD4cjSIWAAZgoAyAgW3ofkCLMwS3LElBV0NA0EwBFNgWK9k29EoNi2XYuwwE40GMRQMHzK4bjhRxHmeSBt0+W9IB+WAOlHXpAWBYZ8FGUhxk3I9oTwu4CKRNV0VRFtHTbM9CXsYlIB7ak6QZNAmWHDkRW5Hj-QLE95IlSUCxlK10WTO1U1bXF2w0tB9UUqdzQM3Uk3-e0030wS4w9RBEwNSdAxDUgw2WSMqzst0HK9X0Gx0vinUEzsczzI0CUA4CK28gswrrSzG2bB0QvivYDgwMS+0k6S2VHNBx1RFyFmnds5wXJAlxXJJ103Ejd1vfdEUvSB70gREP2-X9lQJcDIOg4BfwQ8AgA) to see it in action.

> This is what typechain generates for this output

Assuming you are using the ethers target, TypeChain is creating an ethers return type. ethers returns a "hybrid object-array" syntax, where it places the components in an array and assigns keys to the named components. Since this is not really what is returned from contract functions, ABIType sticks to the logic described above.

**Comment by Yuripetusko** [comment]
Thanks for clarifying, the ethers "hybrid object-array" synthax confused me I think as it appeared as Array
